import * as Class from '@singleware/class';
import { Style } from './style';
/**
 * Stylesheet class.
 */
export declare class Stylesheet extends Class.Null {
    /**
     * Map of selectors.
     */
    private selectorMap;
    /**
     * Gets the representative string of the specified style object.
     * @param style Style object.
     * @returns Returns the representative string generated by the given style object.
     */
    private static getStyleCode;
    /**
     * Returns a new style for the specified selector path.
     * @param selectors Selectors path.
     * @returns Returns the style object.
     */
    select(...selectors: string[]): Style;
    /**
     * Remove all styles from this stylesheet.
     */
    clear(): void;
    /**
     * Convert all styles from this stylesheet to its representative code.
     * @returns Returns the representation code of this stylesheet.
     */
    toString(): string;
}
